### ISSUE TITLE
Runs in the background even if you close the window

### ISSUE THREAD

**Issue by JessusALK** [Teku-Guy/finalProject#2]
Need to create a System.exit(0) condition otherwise the programs just runs in the background forever

**Comment by Teku-Guy** [comment]
Game does not run on my MAC at all and the reason is either you don't stop all threads or the what happens is you click the red X which means dispose the window only but the game is still running so to kill that I added in the KeyInput class press ESC. and it will force quit everything. Eventually the ESC. button will bring up a pause menu.

**Comment by Teku-Guy** [comment]
I get a white screen one of the threads is returning null

**Comment by JessusALK** [comment]
Ahhhh, let's just fix it tomorrow.

What the.. Runs just fine on my PC.

It might be the build file

**Comment by JessusALK** [comment]
Try cloning into another folder or rebuilding the files I don't see anywhere would a thread would hang

**Comment by Teku-Guy** [comment]
I have it's something with the new linked list you made

**Comment by Teku-Guy** [comment]
ok nvm I got it to work
